# Generated by Django 2.0.6 on 2018-06-27 16:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CashInAndOut',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(verbose_name='Số tiền')),
                ('notes', models.CharField(blank=True, max_length=255, verbose_name='Ghi chú')),
                ('time', models.DateField(auto_now=True, verbose_name='Thời gian')),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cash', models.FloatField(verbose_name='Tiền mặt')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='member', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Người dùng',
                'verbose_name_plural': 'Người dùng',
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('cashinandout_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.CashInAndOut')),
                ('type', models.CharField(choices=[('f', 'Ăn'), ('u', 'Dịch vụ'), ('b', 'Mua sắm'), ('e', 'Giải trí'), ('s', 'Học tập'), ('f', 'Gia đình')], max_length=1, verbose_name='Loại chi tiêu')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Member', verbose_name='Người dùng')),
            ],
            options={
                'verbose_name_plural': 'Chi tiêu',
            },
            bases=('main.cashinandout',),
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('cashinandout_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.CashInAndOut')),
                ('type', models.CharField(choices=[('f', 'Thu nhập cố định'), ('i', 'Tiền lãi'), ('b', 'Vay'), ('o', 'Khác')], max_length=1, verbose_name='Loại thu nhập')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Member', verbose_name='Người dùng')),
            ],
            options={
                'verbose_name_plural': 'Thu nhập',
            },
            bases=('main.cashinandout',),
        ),
    ]
